name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ["3.8", "3.9", "3.10", "3.11.0-beta.3"] 

    - name: Run Python Script
      run: ${{ github.workspace }}/bin/getSiteCookie.py   # Path to your Python script
