name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # Set the environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Use the latest version
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can specify the version you want here  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify Python 3

    - name: Run Python Script
      run: ${{ github.workspace }}/bin/getSiteCookie.py   # Path to your Python script
